name: Update GitHub Teams From TXT

on:
  push:
    paths:
      - 'teams/*.txt'

jobs:
  update_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install octokit
          
      - name: Get modified files
        run: |
         modified_files="${{ github.event.head_commit.modified }}"
          echo "Modified files: $modified_files"             

      - name: Update GitHub Teams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          ruby .github/scripts/update_teams_from_txt.rb "${{ github.event.head_commit.modified }}"
