name: Update GitHub Teams From TXT

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'teams/*.txt'

jobs:
  update_teams:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

# Use this if you want to use a GitHub App instead of a PAT, which is recommended
      # - name: GitHub App authentication
      #   uses: peter-murray/authenticate-with-github-app@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}
      #     installation_id: ${{ secrets.INSTALLATION_ID }}  

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install octokit
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35    

      - name: Update GitHub Teams
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          REPOSITORY: ${{ github.repository }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          ruby .github/scripts/update_teams_from_txt.rb "${{ steps.changed-files.outputs.all_changed_files }}"
