name: Update GitHub Teams From TXT

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'teams/*.txt'

jobs:
  update_teams:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install octokit

      - name: Update GitHub Teams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          modified_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          ruby .github/scripts/update_teams_from_txt.rb "$modified_files"
